### ISSUE TITLE
Broken in Gedit 3.14. - libpeas-WARNING **: The 'python' plugin loader has not been enabled.

### ISSUE THREAD

**Issue by sam-at-github** [dtrebbien/gedit-trim-trailing-whitespace-before-saving-plugin#18]
As soon as I try to enable the plugin I get:

    (gedit:32492): libpeas-WARNING **: The 'python' plugin loader has not been enabled

And a red error icon next to the plugin.

> lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.5 (jessie)
Release:	8.5
Codename:	jessie

> gedit --version
gedit - Version 3.14.0

**Comment by sam-at-github** [comment]
Also here https://github.com/trentrichardson/Gedit-Clientside-Plugin/issues/2

**Comment by dtrebbien** [comment]
Hello Sam,

It looks like you are using the Python 2 version. You need to run the Python 3 version with Gedit version 3.8 or higher. If you have cloned the git repo, check out the `master-python3` branch.

Daniel

**Comment by sam-at-github** [comment]
Ah thanks mate. That worked. Skimmed over that bit about >3.8 ... master-python3 ... :).

Can't use gedit without this plugin. Cheers!
